In [1]:
import requests

In [2]:
URL = 'https://realpython.github.io/fake-jobs/'
response = requests.get(URL)

In [3]:
response.status_code

200

In [4]:
response.text

'<!DOCTYPE html>\n<html>\n  <head>\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1">\n    <title>Fake Python</title>\n    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">\n  </head>\n  <body>\n  <section class="section">\n    <div class="container mb-5">\n      <h1 class="title is-1">\n        Fake Python\n      </h1>\n      <p class="subtitle is-3">\n        Fake Jobs for Your Web Scraping Journey\n      </p>\n    </div>\n    <div class="container">\n    <div id="ResultsContainer" class="columns is-multiline">\n    <div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Senior Python Developer</h2>\n        <h3 class="subtitle is-6 company">Payne, Roberts and Davis</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Stewartbury, AA\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Energy engineer</h2>\n        <h3 class="subtitle is-6 company">Vasquez-Davidson</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Christopherville, AA\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/energy-engineer-1.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Legal executive</h2>\n        <h3 class="subtitle is-6 company">Jackson, Chambers and Levy</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Port Ericaburgh, AA\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/legal-executive-2.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Fitness centre manager</h2>\n        <h3 class="subtitle is-6 company">Savage-Bradley</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        East Seanview, AP\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/fitness-centre-manager-3.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Product manager</h2>\n        <h3 class="subtitle is-6 company">Ramirez Inc</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        North Jamieview, AP\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/product-manager-4.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Medical technical officer</h2>\n        <h3 class="subtitle is-6 company">Rogers-Yates</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Davidville, AP\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/medical-technical-officer-5.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Physiological scientist</h2>\n        <h3 class="subtitle is-6 company">Kramer-Klein</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        South Christopher, AE\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/physiological-scientist-6.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Textile designer</h2>\n        <h3 class="subtitle is-6 company">Meyers-Johnson</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Port Jonathan, AE\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/textile-designer-7.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Television floor manager</h2>\n        <h3 class="subtitle is-6 company">Hughes-Williams</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Osbornetown, AE\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/television-floor-manager-8.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Waste management officer</h2>\n        <h3 class="subtitle is-6 company">Jones, Williams and Villa</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Scotttown, AP\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/waste-management-officer-9.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Software Engineer (Python)</h2>\n        <h3 class="subtitle is-6 company">Garcia PLC</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Ericberg, AE\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/software-engineer-python-10.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Interpreter</h2>\n        <h3 class="subtitle is-6 company">Gregory and Sons</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Ramireztown, AE\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/interpreter-11.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Architect</h2>\n        <h3 class="subtitle is-6 company">Clark, Garcia and Sosa</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Figueroaview, AA\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/architect-12.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Meteorologist</h2>\n        <h3 class="subtitle is-6 company">Bush PLC</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Kelseystad, AA\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/meteorologist-13.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Audiological scientist</h2>\n        <h3 class="subtitle is-6 company">Salazar-Meyers</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Williamsburgh, AE\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/audiological-scientist-14.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">English as a second language teacher</h2>\n        <h3 class="subtitle is-6 company">Parker, Murphy and Brooks</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Mitchellburgh, AE\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/english-as-a-second-language-teacher-15.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Surgeon</h2>\n        <h3 class="subtitle is-6 company">Cruz-Brown</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        West Jessicabury, AA\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/surgeon-16.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1" alt="Real Python Logo">\n        </figure>\n      </div>\n      <div class="media-content">\n        <h2 class="title is-5">Equities trader</h2>\n        <h3 class="subtitle is-6 company">Macdonald-Ferguson</h3>\n      </div>\n    </div>\n\n    <div class="content">\n      <p class="location">\n        Maloneshire, AE\n      </p>\n      <p class="is-small has-text-grey">\n        <time datetime="2021-04-08">2021-04-08</time>\n      </p>\n    </div>\n    <footer class="card-footer">\n        <a href="https://www.realpython.com" target="_blank" class="card-footer-item">Learn</a>\n        <a href="https://realpython.github.io/fake-jobs/jobs/equities-trader-17.html" target="_blank" class="card-footer-item">Apply</a>\n    </footer>\n  </div>\n</div>\n</div>\n<div class="column is-half">\n<div class="card">\n  <div class="card-content">\n    <div class="media">\n      <div class="media-left">\n        <figure class="image is-48x48">\n          <img src="h

In [5]:
from bs4 import BeautifulSoup as BS

In [6]:
soup = BS(response.text)

In [7]:
soup

<!DOCTYPE html>

<html>
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>Fake Python</title>
<link href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css" rel="stylesheet"/>
</head>
<body>
<section class="section">
<div class="container mb-5">
<h1 class="title is-1">
        Fake Python
      </h1>
<p class="subtitle is-3">
        Fake Jobs for Your Web Scraping Journey
      </p>
</div>
<div class="container">
<div class="columns is-multiline" id="ResultsContainer">
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Senior Python Developer</h2>
<h3 class="subtitle is-6 company">Payne, Roberts and Davis</h3>
</div>
</div>
<div class="content">
<p class="location">
        Stewartbury, AA
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html" target="_blank">Apply</a>
</footer>
</div>
</div>
</div>
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Energy engineer</h2>
<h3 class="subtitle is-6 company">Vasquez-Davidson</h3>
</div>
</div>
<div class="content">
<p class="location">
        Christopherville, AA
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/energy-engineer-1.html" target="_blank">Apply</a>
</footer>
</div>
</div>
</div>
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Legal executive</h2>
<h3 class="subtitle is-6 company">Jackson, Chambers and Levy</h3>
</div>
</div>
<div class="content">
<p class="location">
        Port Ericaburgh, AA
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/legal-executive-2.html" target="_blank">Apply</a>
</footer>
</div>
</div>
</div>
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Fitness centre manager</h2>
<h3 class="subtitle is-6 company">Savage-Bradley</h3>
</div>
</div>
<div class="content">
<p class="location">
        East Seanview, AP
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/fitness-centre-manager-3.html" target="_blank">Apply</a>
</footer>
</div>
</div>
</div>
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Product manager</h2>
<h3 class="subtitle is-6 company">Ramirez Inc</h3>
</div>
</div>
<div class="content">
<p class="location">
        North Jamieview, AP
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/product-manager-4.html" target="_blank">Apply</a>
</footer>
</div>
</div>
</div>
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Medical technical officer</h2>
<h3 class="subtitle is-6 company">Rogers-Yates</h3>
</div>
</div>
<div class="content">
<p class="location">
        Davidville, AP
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/medical-technical-officer-5.html" target="_blank">Apply</a>
</footer>
</div>
</div>
</div>
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Physiological scientist</h2>
<h3 class="subtitle is-6 company">Kramer-Klein</h3>
</div>
</div>
<div class="content">
<p class="location">
        South Christopher, AE
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/physiological-scientist-6.html" target="_blank">Apply</a>
</footer>
</div>
</div>
</div>
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Textile designer</h2>
<h3 class="subtitle is-6 company">Meyers-Johnson</h3>
</div>
</div>
<div class="content">
<p class="location">
        Port Jonathan, AE
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/textile-designer-7.html" target="_blank">Apply</a>
</footer>
</div>
</div>
</div>
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Television floor manager</h2>
<h3 class="subtitle is-6 company">Hughes-Williams</h3>
</div>
</div>
<div class="content">
<p class="location">
        Osbornetown, AE
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/television-floor-manager-8.html" target="_blank">Apply</a>
</footer>
</div>
</div>
</div>
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Waste management officer</h2>
<h3 class="subtitle is-6 company">Jones, Williams and Villa</h3>
</div>
</div>
<div class="content">
<p class="location">
        Scotttown, AP
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/waste-management-officer-9.html" target="_blank">Apply</a>
</footer>
</div>
</div>
</div>
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Software Engineer (Python)</h2>
<h3 class="subtitle is-6 company">Garcia PLC</h3>
</div>
</div>
<div class="content">
<p class="location">
        Ericberg, AE
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/software-engineer-python-10.html" target="_blank">Apply</a>
</footer>
</div>
</div>
</div>
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Interpreter</h2>
<h3 class="subtitle is-6 company">Gregory and Sons</h3>
</div>
</div>
<div class="content">
<p class="location">
        Ramireztown, AE
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/interpreter-11.html" target="_blank">Apply</a>
</footer>
</div>
</div>
</div>
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Architect</h2>
<h3 class="subtitle is-6 company">Clark, Garcia and Sosa</h3>
</div>
</div>
<div class="content">
<p class="location">
        Figueroaview, AA
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/architect-12.html" target="_blank">Apply</a>
</footer>
</div>
</div>
</div>
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Meteorologist</h2>
<h3 class="subtitle is-6 company">Bush PLC</h3>
</div>
</div>
<div class="content">
<p class="location">
        Kelseystad, AA
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/meteorologist-13.html" target="_blank">Apply</a>
</footer>
</div>
</div>
</div>
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Audiological scientist</h2>
<h3 class="subtitle is-6 company">Salazar-Meyers</h3>
</div>
</div>
<div class="content">
<p class="location">
        Williamsburgh, AE
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/audiological-scientist-14.html" target="_blank">Apply</a>
</footer>
</div>
</div>
</div>
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">English as a second language teacher</h2>
<h3 class="subtitle is-6 company">Parker, Murphy and Brooks</h3>
</div>
</div>
<div class="content">
<p class="location">
        Mitchellburgh, AE
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/english-as-a-second-language-teacher-15.html" target="_blank">Apply</a>
</footer>
</div>
</div>
</div>
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Surgeon</h2>
<h3 class="subtitle is-6 company">Cruz-Brown</h3>
</div>
</div>
<div class="content">
<p class="location">
        West Jessicabury, AA
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/surgeon-16.html" target="_blank">Apply</a>
</footer>
</div>
</div>
</div>
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Equities trader</h2>
<h3 class="subtitle is-6 company">Macdonald-Ferguson</h3>
</div>
</div>
<div class="content">
<p class="location">
        Maloneshire, AE
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/equities-trader-17.html" target="_blank">Apply</a>
</footer>
</div>
</div>
</div>
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Newspaper journalist</h2>
<h3 class="subtitle is-6 company">Williams, Peterson and Rojas</h3>
</div>
</div>
<div class="content">
<p class="location">
        Johnsonton, AA
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/newspaper-journalist-18.html" target="_blank">Apply</a>
</footer>
</div>
</div>
</div>
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Materials engineer</h2>
<h3 class="subtitle is-6 company">Smith and Sons</h3>
</div>
</div>
<div class="content">
<p class="location">
        South Davidtown, AP
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/materials-engineer-19.html" target="_blank">Apply</a>
</footer>
</div>
</div>
</div>
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Python Programmer (Entry-Level)</h2>
<h3 class="subtitle is-6 company">Moss, Duncan and Allen</h3>
</div>
</div>
<div class="content">
<p class="location">
        Port Sara, AE
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-20.html" target="_blank">Apply</a>
</footer>
</div>
</div>
</div>
<div class="column is-half">
<div class="card">
<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Product/process development scientist</h2>
<h3 class="subtitle is-6 company">Gomez-Carroll</h3>
</div>
</div>
<div class="content">
<p class="location">

In [8]:
print(soup.prettify())

<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <title>
   Fake Python
  </title>
  <link href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css" rel="stylesheet"/>
 </head>
 <body>
  <section class="section">
   <div class="container mb-5">
    <h1 class="title is-1">
     Fake Python
    </h1>
    <p class="subtitle is-3">
     Fake Jobs for Your Web Scraping Journey
    </p>
   </div>
   <div class="container">
    <div class="columns is-multiline" id="ResultsContainer">
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Senior Python Developer
          </h2>
          <h3 class="subtitle is-6 company">
           Payne, Roberts and Davis
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Stewartbury, AA
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Energy engineer
          </h2>
          <h3 class="subtitle is-6 company">
           Vasquez-Davidson
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Christopherville, AA
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/energy-engineer-1.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Legal executive
          </h2>
          <h3 class="subtitle is-6 company">
           Jackson, Chambers and Levy
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Port Ericaburgh, AA
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/legal-executive-2.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Fitness centre manager
          </h2>
          <h3 class="subtitle is-6 company">
           Savage-Bradley
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          East Seanview, AP
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/fitness-centre-manager-3.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Product manager
          </h2>
          <h3 class="subtitle is-6 company">
           Ramirez Inc
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          North Jamieview, AP
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/product-manager-4.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Medical technical officer
          </h2>
          <h3 class="subtitle is-6 company">
           Rogers-Yates
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Davidville, AP
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/medical-technical-officer-5.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Physiological scientist
          </h2>
          <h3 class="subtitle is-6 company">
           Kramer-Klein
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          South Christopher, AE
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/physiological-scientist-6.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Textile designer
          </h2>
          <h3 class="subtitle is-6 company">
           Meyers-Johnson
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Port Jonathan, AE
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/textile-designer-7.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Television floor manager
          </h2>
          <h3 class="subtitle is-6 company">
           Hughes-Williams
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Osbornetown, AE
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/television-floor-manager-8.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Waste management officer
          </h2>
          <h3 class="subtitle is-6 company">
           Jones, Williams and Villa
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Scotttown, AP
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/waste-management-officer-9.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Software Engineer (Python)
          </h2>
          <h3 class="subtitle is-6 company">
           Garcia PLC
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Ericberg, AE
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/software-engineer-python-10.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Interpreter
          </h2>
          <h3 class="subtitle is-6 company">
           Gregory and Sons
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Ramireztown, AE
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/interpreter-11.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Architect
          </h2>
          <h3 class="subtitle is-6 company">
           Clark, Garcia and Sosa
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Figueroaview, AA
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/architect-12.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Meteorologist
          </h2>
          <h3 class="subtitle is-6 company">
           Bush PLC
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Kelseystad, AA
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/meteorologist-13.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           Audiological scientist
          </h2>
          <h3 class="subtitle is-6 company">
           Salazar-Meyers
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Williamsburgh, AE
         </p>
         <p class="is-small has-text-grey">
          <time datetime="2021-04-08">
           2021-04-08
          </time>
         </p>
        </div>
        <footer class="card-footer">
         <a class="card-footer-item" href="https://www.realpython.com" target="_blank">
          Learn
         </a>
         <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/audiological-scientist-14.html" target="_blank">
          Apply
         </a>
        </footer>
       </div>
      </div>
     </div>
     <div class="column is-half">
      <div class="card">
       <div class="card-content">
        <div class="media">
         <div class="media-left">
          <figure class="image is-48x48">
           <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
          </figure>
         </div>
         <div class="media-content">
          <h2 class="title is-5">
           English as a second language teacher
          </h2>
          <h3 class="subtitle is-6 company">
           Parker, Murphy and Brooks
          </h3>
         </div>
        </div>
        <div class="content">
         <p class="location">
          Mitchellburgh, AE
         </p>
         <p class="is-small has-text-grey">

In [9]:
soup.find('h2', attrs={'class' : 'title is-5'})

In [10]:
soup.find('h2', attrs={'class' : 'title is-5'}).text

'Senior Python Developer'

In [11]:
soup.find('h2', attrs={'class' : 'title is-5'}).text.strip()

'Senior Python Developer'

In [12]:
first_job = soup.find('h2', attrs={'class' : 'title is-5'})

In [13]:
first_job.text.strip()

'Senior Python Developer'

In [14]:
soup.find_all('h2', attrs={'class' : 'title is-5'})

[<h2 class="title is-5">Senior Python Developer</h2>,
 <h2 class="title is-5">Energy engineer</h2>,
 <h2 class="title is-5">Legal executive</h2>,
 <h2 class="title is-5">Fitness centre manager</h2>,
 <h2 class="title is-5">Product manager</h2>,
 <h2 class="title is-5">Medical technical officer</h2>,
 <h2 class="title is-5">Physiological scientist</h2>,
 <h2 class="title is-5">Textile designer</h2>,
 <h2 class="title is-5">Television floor manager</h2>,
 <h2 class="title is-5">Waste management officer</h2>,
 <h2 class="title is-5">Software Engineer (Python)</h2>,
 <h2 class="title is-5">Interpreter</h2>,
 <h2 class="title is-5">Architect</h2>,
 <h2 class="title is-5">Meteorologist</h2>,
 <h2 class="title is-5">Audiological scientist</h2>,
 <h2 class="title is-5">English as a second language teacher</h2>,
 <h2 class="title is-5">Surgeon</h2>,
 <h2 class="title is-5">Equities trader</h2>,
 <h2 class="title is-5">Newspaper journalist</h2>,
 <h2 class="title is-5">Materials engineer</h2>,
 <h2 class="title is-5">Python Programmer (Entry-Level)</h2>,
 <h2 class="title is-5">Product/process development scientist</h2>,
 <h2 class="title is-5">Scientist, research (maths)</h2>,
 <h2 class="title is-5">Ecologist</h2>,
 <h2 class="title is-5">Materials engineer</h2>,
 <h2 class="title is-5">Historic buildings inspector/conservation officer</h2>,
 <h2 class="title is-5">Data scientist</h2>,
 <h2 class="title is-5">Psychiatrist</h2>,
 <h2 class="title is-5">Structural engineer</h2>,
 <h2 class="title is-5">Immigration officer</h2>,
 <h2 class="title is-5">Python Programmer (Entry-Level)</h2>,
 <h2 class="title is-5">Neurosurgeon</h2>,
 <h2 class="title is-5">Broadcast engineer</h2>,
 <h2 class="title is-5">Make</h2>,
 <h2 class="title is-5">Nurse, adult</h2>,
 <h2 class="title is-5">Air broker</h2>,
 <h2 class="title is-5">Editor, film/video</h2>,
 <h2 class="title is-5">Production assistant, radio</h2>,
 <h2 class="title is-5">Engineer, communications</h2>,
 <h2 class="title is-5">Sales executive</h2>,
 <h2 class="title is-5">Software Developer (Python)</h2>,
 <h2 class="title is-5">Futures trader</h2>,
 <h2 class="title is-5">Tour manager</h2>,
 <h2 class="title is-5">Cytogeneticist</h2>,
 <h2 class="title is-5">Designer, multimedia</h2>,
 <h2 class="title is-5">Trade union research officer</h2>,
 <h2 class="title is-5">Chemist, analytical</h2>,
 <h2 class="title is-5">Programmer, multimedia</h2>,
 <h2 class="title is-5">Engineer, broadcasting (operations)</h2>,
 <h2 class="title is-5">Teacher, primary school</h2>,
 <h2 class="title is-5">Python Developer</h2>,
 <h2 class="title is-5">Manufacturing systems engineer</h2>,
 <h2 class="title is-5">Producer, television/film/video</h2>,
 <h2 class="title is-5">Scientist, forensic</h2>,
 <h2 class="title is-5">Bonds trader</h2>,
 <h2 class="title is-5">Editorial assistant</h2>,
 <h2 class="title is-5">Photographer</h2>,
 <h2 class="title is-5">Retail banker</h2>,
 <h2 class="title is-5">Jewellery designer</h2>,
 <h2 class="title is-5">Ophthalmologist</h2>,
 <h2 class="title is-5">Back-End Web Developer (Python, Django)</h2>,
 <h2 class="title is-5">Licensed conveyancer</h2>,
 <h2 class="title is-5">Futures trader</h2>,
 <h2 class="title is-5">Counselling psychologist</h2>,
 <h2 class="title is-5">Insurance underwriter</h2>,
 <h2 class="title is-5">Engineer, automotive</h2>,
 <h2 class="title is-5">Producer, radio</h2>,
 <h2 class="title is-5">Dispensing optician</h2>,
 <h2 class="title is-5">Designer, fashion/clothing</h2>,
 <h2 class="title is-5">Chartered loss adjuster</h2>,
 <h2 class="title is-5">Back-End Web Developer (Python, Django)</h2>,
 <h2 class="title is-5">Forest/woodland manager</h2>,
 <h2 class="title is-5">Clinical cytogeneticist</h2>,
 <h2 class="title is-5">Print production planner</h2>,
 <h2 class="title is-5">Systems developer</h2>,
 <h2 class="title is-5">Graphic designer</h2>,
 <h2 class="title is-5">Writer</h2>,
 <h2 class="title is-5">Field seismologist</h2>,
 <h2 class="title is-5">Chief Strategy Officer</h2>,
 <h2 class="title is-5">Air cabin crew</h2>,
 <h2 class="title is-5">Python Programmer (Entry-Level)</h2>,
 <h2 class="title is-5">Warden/ranger</h2>,
 <h2 class="title is-5">Sports therapist</h2>,
 <h2 class="title is-5">Arts development officer</h2>,
 <h2 class="title is-5">Printmaker</h2>,
 <h2 class="title is-5">Health and safety adviser</h2>,
 <h2 class="title is-5">Manufacturing systems engineer</h2>,
 <h2 class="title is-5">Programmer, applications</h2>,
 <h2 class="title is-5">Medical physicist</h2>,
 <h2 class="title is-5">Media planner</h2>,
 <h2 class="title is-5">Software Developer (Python)</h2>,
 <h2 class="title is-5">Surveyor, land/geomatics</h2>,
 <h2 class="title is-5">Legal executive</h2>,
 <h2 class="title is-5">Librarian, academic</h2>,
 <h2 class="title is-5">Barrister</h2>,
 <h2 class="title is-5">Museum/gallery exhibitions officer</h2>,
 <h2 class="title is-5">Radiographer, diagnostic</h2>,
 <h2 class="title is-5">Database administrator</h2>,
 <h2 class="title is-5">Furniture designer</h2>,
 <h2 class="title is-5">Ship broker</h2>]

In [15]:
all_titles = soup.find_all('h2', attrs={'class' : 'title is-5'})

In [16]:
job_titles = [title.text.strip() for title in all_titles]

In [17]:
len(job_titles)

100

In [18]:
job_titles[0]

'Senior Python Developer'

In [19]:
job_titles[-1]

'Ship broker'

In [20]:
soup.find_all('h3', attrs={'class' : 'subtitle is-6 company'})

[<h3 class="subtitle is-6 company">Payne, Roberts and Davis</h3>,
 <h3 class="subtitle is-6 company">Vasquez-Davidson</h3>,
 <h3 class="subtitle is-6 company">Jackson, Chambers and Levy</h3>,
 <h3 class="subtitle is-6 company">Savage-Bradley</h3>,
 <h3 class="subtitle is-6 company">Ramirez Inc</h3>,
 <h3 class="subtitle is-6 company">Rogers-Yates</h3>,
 <h3 class="subtitle is-6 company">Kramer-Klein</h3>,
 <h3 class="subtitle is-6 company">Meyers-Johnson</h3>,
 <h3 class="subtitle is-6 company">Hughes-Williams</h3>,
 <h3 class="subtitle is-6 company">Jones, Williams and Villa</h3>,
 <h3 class="subtitle is-6 company">Garcia PLC</h3>,
 <h3 class="subtitle is-6 company">Gregory and Sons</h3>,
 <h3 class="subtitle is-6 company">Clark, Garcia and Sosa</h3>,
 <h3 class="subtitle is-6 company">Bush PLC</h3>,
 <h3 class="subtitle is-6 company">Salazar-Meyers</h3>,
 <h3 class="subtitle is-6 company">Parker, Murphy and Brooks</h3>,
 <h3 class="subtitle is-6 company">Cruz-Brown</h3>,
 <h3 class="subtitle is-6 company">Macdonald-Ferguson</h3>,
 <h3 class="subtitle is-6 company">Williams, Peterson and Rojas</h3>,
 <h3 class="subtitle is-6 company">Smith and Sons</h3>,
 <h3 class="subtitle is-6 company">Moss, Duncan and Allen</h3>,
 <h3 class="subtitle is-6 company">Gomez-Carroll</h3>,
 <h3 class="subtitle is-6 company">Manning, Welch and Herring</h3>,
 <h3 class="subtitle is-6 company">Lee, Gutierrez and Brown</h3>,
 <h3 class="subtitle is-6 company">Davis, Serrano and Cook</h3>,
 <h3 class="subtitle is-6 company">Smith LLC</h3>,
 <h3 class="subtitle is-6 company">Thomas Group</h3>,
 <h3 class="subtitle is-6 company">Silva-King</h3>,
 <h3 class="subtitle is-6 company">Pierce-Long</h3>,
 <h3 class="subtitle is-6 company">Walker-Simpson</h3>,
 <h3 class="subtitle is-6 company">Cooper and Sons</h3>,
 <h3 class="subtitle is-6 company">Donovan, Gonzalez and Figueroa</h3>,
 <h3 class="subtitle is-6 company">Morgan, Butler and Bennett</h3>,
 <h3 class="subtitle is-6 company">Snyder-Lee</h3>,
 <h3 class="subtitle is-6 company">Harris PLC</h3>,
 <h3 class="subtitle is-6 company">Washington PLC</h3>,
 <h3 class="subtitle is-6 company">Brown, Price and Campbell</h3>,
 <h3 class="subtitle is-6 company">Mcgee PLC</h3>,
 <h3 class="subtitle is-6 company">Dixon Inc</h3>,
 <h3 class="subtitle is-6 company">Thompson, Sheppard and Ward</h3>,
 <h3 class="subtitle is-6 company">Adams-Brewer</h3>,
 <h3 class="subtitle is-6 company">Schneider-Brady</h3>,
 <h3 class="subtitle is-6 company">Gonzales-Frank</h3>,
 <h3 class="subtitle is-6 company">Smith-Wong</h3>,
 <h3 class="subtitle is-6 company">Pierce-Herrera</h3>,
 <h3 class="subtitle is-6 company">Aguilar, Rivera and Quinn</h3>,
 <h3 class="subtitle is-6 company">Lowe, Barnes and Thomas</h3>,
 <h3 class="subtitle is-6 company">Lewis, Gonzalez and Vasquez</h3>,
 <h3 class="subtitle is-6 company">Taylor PLC</h3>,
 <h3 class="subtitle is-6 company">Oliver, Jones and Ramirez</h3>,
 <h3 class="subtitle is-6 company">Rivera and Sons</h3>,
 <h3 class="subtitle is-6 company">Garcia PLC</h3>,
 <h3 class="subtitle is-6 company">Johnson, Wells and Kramer</h3>,
 <h3 class="subtitle is-6 company">Gonzalez LLC</h3>,
 <h3 class="subtitle is-6 company">Morgan, White and Macdonald</h3>,
 <h3 class="subtitle is-6 company">Robinson-Fitzpatrick</h3>,
 <h3 class="subtitle is-6 company">Waters, Wilson and Hoover</h3>,
 <h3 class="subtitle is-6 company">Hill LLC</h3>,
 <h3 class="subtitle is-6 company">Li-Gregory</h3>,
 <h3 class="subtitle is-6 company">Fisher, Ryan and Coleman</h3>,
 <h3 class="subtitle is-6 company">Stewart-Alexander</h3>,
 <h3 class="subtitle is-6 company">Abbott and Sons</h3>,
 <h3 class="subtitle is-6 company">Bryant, Santana and Davenport</h3>,
 <h3 class="subtitle is-6 company">Smith PLC</h3>,
 <h3 class="subtitle is-6 company">Patterson-Singh</h3>,
 <h3 class="subtitle is-6 company">Martinez-Berry</h3>,
 <h3 class="subtitle is-6 company">May, Taylor and Fisher</h3>,
 <h3 class="subtitle is-6 company">Bailey, Owen and Thompson</h3>,
 <h3 class="subtitle is-6 company">Vasquez Ltd</h3>,
 <h3 class="subtitle is-6 company">Leblanc LLC</h3>,
 <h3 class="subtitle is-6 company">Jackson, Ali and Mckee</h3>,
 <h3 class="subtitle is-6 company">Blankenship, Knight and Powell</h3>,
 <h3 class="subtitle is-6 company">Patton, Haynes and Jones</h3>,
 <h3 class="subtitle is-6 company">Wood Inc</h3>,
 <h3 class="subtitle is-6 company">Collins Group</h3>,
 <h3 class="subtitle is-6 company">Flores-Nelson</h3>,
 <h3 class="subtitle is-6 company">Mitchell, Jones and Olson</h3>,
 <h3 class="subtitle is-6 company">Howard Group</h3>,
 <h3 class="subtitle is-6 company">Kramer-Edwards</h3>,
 <h3 class="subtitle is-6 company">Berry-Houston</h3>,
 <h3 class="subtitle is-6 company">Mathews Inc</h3>,
 <h3 class="subtitle is-6 company">Riley-Johnson</h3>,
 <h3 class="subtitle is-6 company">Spencer and Sons</h3>,
 <h3 class="subtitle is-6 company">Camacho-Sanchez</h3>,
 <h3 class="subtitle is-6 company">Oliver and Sons</h3>,
 <h3 class="subtitle is-6 company">Eaton PLC</h3>,
 <h3 class="subtitle is-6 company">Stanley-Frederick</h3>,
 <h3 class="subtitle is-6 company">Bradley LLC</h3>,
 <h3 class="subtitle is-6 company">Parker, Goodwin and Zavala</h3>,
 <h3 class="subtitle is-6 company">Kim-Miles</h3>,
 <h3 class="subtitle is-6 company">Moreno-Rodriguez</h3>,
 <h3 class="subtitle is-6 company">Brown-Ortiz</h3>,
 <h3 class="subtitle is-6 company">Hartman PLC</h3>,
 <h3 class="subtitle is-6 company">Brooks Inc</h3>,
 <h3 class="subtitle is-6 company">Washington-Castillo</h3>,
 <h3 class="subtitle is-6 company">Nguyen, Yoder and Petty</h3>,
 <h3 class="subtitle is-6 company">Holder LLC</h3>,
 <h3 class="subtitle is-6 company">Yates-Ferguson</h3>,
 <h3 class="subtitle is-6 company">Ortega-Lawrence</h3>,
 <h3 class="subtitle is-6 company">Fuentes, Walls and Castro</h3>]

In [21]:
all_companies = soup.find_all('h3', attrs={'class' : 'subtitle is-6 company'})

In [22]:
company_list = [title.text.strip() for title in all_companies]

In [23]:
company_list[0]

'Payne, Roberts and Davis'

In [24]:
company_list[-1]

'Fuentes, Walls and Castro'

In [25]:
all_locations = soup.find_all('p', attrs={'class' : 'location'})

In [26]:
all_locations

[<p class="location">
         Stewartbury, AA
       </p>,
 <p class="location">
         Christopherville, AA
       </p>,
 <p class="location">
         Port Ericaburgh, AA
       </p>,
 <p class="location">
         East Seanview, AP
       </p>,
 <p class="location">
         North Jamieview, AP
       </p>,
 <p class="location">
         Davidville, AP
       </p>,
 <p class="location">
         South Christopher, AE
       </p>,
 <p class="location">
         Port Jonathan, AE
       </p>,
 <p class="location">
         Osbornetown, AE
       </p>,
 <p class="location">
         Scotttown, AP
       </p>,
 <p class="location">
         Ericberg, AE
       </p>,
 <p class="location">
         Ramireztown, AE
       </p>,
 <p class="location">
         Figueroaview, AA
       </p>,
 <p class="location">
         Kelseystad, AA
       </p>,
 <p class="location">
         Williamsburgh, AE
       </p>,
 <p class="location">
         Mitchellburgh, AE
       </p>,
 <p class="location">
         West Jessicabury, AA
       </p>,
 <p class="location">
         Maloneshire, AE
       </p>,
 <p class="location">
         Johnsonton, AA
       </p>,
 <p class="location">
         South Davidtown, AP
       </p>,
 <p class="location">
         Port Sara, AE
       </p>,
 <p class="location">
         Marktown, AA
       </p>,
 <p class="location">
         Laurenland, AE
       </p>,
 <p class="location">
         Lauraton, AP
       </p>,
 <p class="location">
         South Tammyberg, AP
       </p>,
 <p class="location">
         North Brandonville, AP
       </p>,
 <p class="location">
         Port Robertfurt, AA
       </p>,
 <p class="location">
         Burnettbury, AE
       </p>,
 <p class="location">
         Herbertside, AA
       </p>,
 <p class="location">
         Christopherport, AP
       </p>,
 <p class="location">
         West Victor, AE
       </p>,
 <p class="location">
         Port Aaron, AP
       </p>,
 <p class="location">
         Loribury, AA
       </p>,
 <p class="location">
         Angelastad, AP
       </p>,
 <p class="location">
         Larrytown, AE
       </p>,
 <p class="location">
         West Colin, AP
       </p>,
 <p class="location">
         West Stephanie, AP
       </p>,
 <p class="location">
         Laurentown, AP
       </p>,
 <p class="location">
         Wrightberg, AP
       </p>,
 <p class="location">
         Alberttown, AE
       </p>,
 <p class="location">
         Brockburgh, AE
       </p>,
 <p class="location">
         North Jason, AE
       </p>,
 <p class="location">
         Arnoldhaven, AE
       </p>,
 <p class="location">
         Lake Destiny, AP
       </p>,
 <p class="location">
         South Timothyburgh, AP
       </p>,
 <p class="location">
         New Jimmyton, AE
       </p>,
 <p class="location">
         New Lucasbury, AP
       </p>,
 <p class="location">
         Port Cory, AE
       </p>,
 <p class="location">
         Gileston, AA
       </p>,
 <p class="location">
         Cindyshire, AA
       </p>,
 <p class="location">
         East Michaelfort, AA
       </p>,
 <p class="location">
         Joybury, AE
       </p>,
 <p class="location">
         Emmatown, AE
       </p>,
 <p class="location">
         Colehaven, AP
       </p>,
 <p class="location">
         Port Coryton, AE
       </p>,
 <p class="location">
         Amyborough, AA
       </p>,
 <p class="location">
         Reynoldsville, AA
       </p>,
 <p class="location">
         Port Billy, AP
       </p>,
 <p class="location">
         Adamburgh, AA
       </p>,
 <p class="location">
         Wilsonmouth, AA
       </p>,
 <p class="location">
         South Kimberly, AA
       </p>,
 <p class="location">
         Benjaminland, AP
       </p>,
 <p class="location">
         Zacharyport, AA
       </p>,
 <p class="location">
         Port Devonville, AE
       </p>,
 <p class="location">
         East Thomas, AE
       </p>,
 <p class="location">
         New Jeffrey, AP
       </p>,
 <p class="location">
         Davidside, AA
       </p>,
 <p class="location">
         Jamesville, AA
       </p>,
 <p class="location">
         New Kelly, AP
       </p>,
 <p class="location">
         Lake Antonio, AA
       </p>,
 <p class="location">
         New Elizabethside, AA
       </p>,
 <p class="location">
         Millsbury, AE
       </p>,
 <p class="location">
         Lloydton, AP
       </p>,
 <p class="location">
         Port Jeremy, AA
       </p>,
 <p class="location">
         New Elizabethtown, AA
       </p>,
 <p class="location">
         Charlesstad, AE
       </p>,
 <p class="location">
         Josephbury, AE
       </p>,
 <p class="location">
         Seanfurt, AA
       </p>,
 <p class="location">
         Williambury, AA
       </p>,
 <p class="location">
         South Jorgeside, AP
       </p>,
 <p class="location">
         Robertborough, AP
       </p>,
 <p class="location">
         South Saratown, AP
       </p>,
 <p class="location">
         Hullview, AA
       </p>,
 <p class="location">
         Philipland, AP
       </p>,
 <p class="location">
         North Patty, AE
       </p>,
 <p class="location">
         North Stephen, AE
       </p>,
 <p class="location">
         Stevensland, AP
       </p>,
 <p class="location">
         Reyesstad, AE
       </p>,
 <p class="location">
         Bellberg, AP
       </p>,
 <p class="location">
         North Johnland, AE
       </p>,
 <p class="location">
         Martinezburgh, AE
       </p>,
 <p class="location">
         Joshuatown, AE
       </p>,
 <p class="location">
         West Ericstad, AA
       </p>,
 <p class="location">
         Tuckertown, AE
       </p>,
 <p class="location">
         Perezton, AE
       </p>,
 <p class="location">
         Lake Abigail, AE
       </p>,
 <p class="location">
         Jacobshire, AP
       </p>,
 <p class="location">
         Port Susan, AE
       </p>,
 <p class="location">
         North Tiffany, AA
       </p>,
 <p class="location">
         Michelleville, AP
       </p>]

In [27]:
location_list = [title.text.strip() for title in all_locations]

In [28]:
location_list

['Stewartbury, AA',
 'Christopherville, AA',
 'Port Ericaburgh, AA',
 'East Seanview, AP',
 'North Jamieview, AP',
 'Davidville, AP',
 'South Christopher, AE',
 'Port Jonathan, AE',
 'Osbornetown, AE',
 'Scotttown, AP',
 'Ericberg, AE',
 'Ramireztown, AE',
 'Figueroaview, AA',
 'Kelseystad, AA',
 'Williamsburgh, AE',
 'Mitchellburgh, AE',
 'West Jessicabury, AA',
 'Maloneshire, AE',
 'Johnsonton, AA',
 'South Davidtown, AP',
 'Port Sara, AE',
 'Marktown, AA',
 'Laurenland, AE',
 'Lauraton, AP',
 'South Tammyberg, AP',
 'North Brandonville, AP',
 'Port Robertfurt, AA',
 'Burnettbury, AE',
 'Herbertside, AA',
 'Christopherport, AP',
 'West Victor, AE',
 'Port Aaron, AP',
 'Loribury, AA',
 'Angelastad, AP',
 'Larrytown, AE',
 'West Colin, AP',
 'West Stephanie, AP',
 'Laurentown, AP',
 'Wrightberg, AP',
 'Alberttown, AE',
 'Brockburgh, AE',
 'North Jason, AE',
 'Arnoldhaven, AE',
 'Lake Destiny, AP',
 'South Timothyburgh, AP',
 'New Jimmyton, AE',
 'New Lucasbury, AP',
 'Port Cory, AE',
 'Gileston, AA',
 'Cindyshire, AA',
 'East Michaelfort, AA',
 'Joybury, AE',
 'Emmatown, AE',
 'Colehaven, AP',
 'Port Coryton, AE',
 'Amyborough, AA',
 'Reynoldsville, AA',
 'Port Billy, AP',
 'Adamburgh, AA',
 'Wilsonmouth, AA',
 'South Kimberly, AA',
 'Benjaminland, AP',
 'Zacharyport, AA',
 'Port Devonville, AE',
 'East Thomas, AE',
 'New Jeffrey, AP',
 'Davidside, AA',
 'Jamesville, AA',
 'New Kelly, AP',
 'Lake Antonio, AA',
 'New Elizabethside, AA',
 'Millsbury, AE',
 'Lloydton, AP',
 'Port Jeremy, AA',
 'New Elizabethtown, AA',
 'Charlesstad, AE',
 'Josephbury, AE',
 'Seanfurt, AA',
 'Williambury, AA',
 'South Jorgeside, AP',
 'Robertborough, AP',
 'South Saratown, AP',
 'Hullview, AA',
 'Philipland, AP',
 'North Patty, AE',
 'North Stephen, AE',
 'Stevensland, AP',
 'Reyesstad, AE',
 'Bellberg, AP',
 'North Johnland, AE',
 'Martinezburgh, AE',
 'Joshuatown, AE',
 'West Ericstad, AA',
 'Tuckertown, AE',
 'Perezton, AE',
 'Lake Abigail, AE',
 'Jacobshire, AP',
 'Port Susan, AE',
 'North Tiffany, AA',
 'Michelleville, AP']

In [29]:
location_list[0]

'Stewartbury, AA'

In [30]:
location_list[-1]

'Michelleville, AP'

In [31]:
all_posting_dates = soup.find_all('time', attrs={'datetime' : '2021-04-08'})

In [32]:
all_posting_dates

[<time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>,
 <time datetime="2021-04-08">2021-04-08</time>]

In [33]:
posting_dates = [title.text.strip() for title in all_posting_dates]

In [34]:
posting_dates

['2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08',
 '2021-04-08']

In [35]:
import pandas as pd

In [36]:
jobs_table = pd.DataFrame({'Job Title' : job_titles, 'Company' : company_list, 'Location' : location_list, 'Posting Date' : posting_dates})

In [37]:
jobs_table.shape

(100, 4)

In [38]:
jobs_table.head()

,Job Title,Company,Location,Posting Date
0,Senior Python Developer,"Payne, Roberts and Davis","Stewartbury, AA",2021-04-08
1,Energy engineer,Vasquez-Davidson,"Christopherville, AA",2021-04-08
2,Legal executive,"Jackson, Chambers and Levy","Port Ericaburgh, AA",2021-04-08
3,Fitness centre manager,Savage-Bradley,"East Seanview, AP",2021-04-08
4,Product manager,Ramirez Inc,"North Jamieview, AP",2021-04-08

In [39]:
jobs_table.tail()

,Job Title,Company,Location,Posting Date
95,Museum/gallery exhibitions officer,"Nguyen, Yoder and Petty","Lake Abigail, AE",2021-04-08
96,"Radiographer, diagnostic",Holder LLC,"Jacobshire, AP",2021-04-08
97,Database administrator,Yates-Ferguson,"Port Susan, AE",2021-04-08
98,Furniture designer,Ortega-Lawrence,"North Tiffany, AA",2021-04-08
99,Ship broker,"Fuentes, Walls and Castro","Michelleville, AP",2021-04-08

In [40]:
soup.find_all('a href', attrs={'class' : 'card-footer-item'})

[]

In [41]:
urls = soup.find_all('a')
type(urls)

bs4.element.ResultSet

In [42]:
len(urls)

200

In [43]:
first_url = urls[0]
type(first_url)

bs4.element.Tag

In [44]:
first_url

In [45]:
for link in urls[:6]:
    print(link.text.strip())

Learn
Apply
Learn
Apply
Learn
Apply

In [46]:
apply_urls = []
for link in urls:
    if link.text.strip() == 'Apply':
        apply_urls.append(link.get('href'))

In [47]:
len(apply_urls)

100

In [48]:
apply_urls[0]

'https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html'

In [49]:
jobs_table['Apply'] = apply_urls

In [50]:
jobs_table.head()

,Job Title,Company,Location,Posting Date,Apply
0,Senior Python Developer,"Payne, Roberts and Davis","Stewartbury, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/se...
1,Energy engineer,Vasquez-Davidson,"Christopherville, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/en...
2,Legal executive,"Jackson, Chambers and Levy","Port Ericaburgh, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/le...
3,Fitness centre manager,Savage-Bradley,"East Seanview, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/fi...
4,Product manager,Ramirez Inc,"North Jamieview, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/pr...

In [51]:
jobs_table.loc[[0, 10, 22], ['Job Title', 'Apply']]

,Job Title,Apply
0,Senior Python Developer,https://realpython.github.io/fake-jobs/jobs/se...
10,Software Engineer (Python),https://realpython.github.io/fake-jobs/jobs/so...
22,"Scientist, research (maths)",https://realpython.github.io/fake-jobs/jobs/sc...

In [52]:
pd.set_option('display.max_colwidth', None)

In [53]:
jobs_table.loc[[0, 10, 22], ['Job Title', 'Apply']]

,Job Title,Apply
0,Senior Python Developer,https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html
10,Software Engineer (Python),https://realpython.github.io/fake-jobs/jobs/software-engineer-python-10.html
22,"Scientist, research (maths)",https://realpython.github.io/fake-jobs/jobs/scientist-research-maths-22.html

In [54]:
url_title = jobs_table['Job Title'].str.lower().str.replace(' ', '-')
url_title.loc[[0, 10, 22]]

0         senior-python-developer
10     software-engineer-(python)
22    scientist,-research-(maths)
Name: Job Title, dtype: str

In [55]:
url_title = (jobs_table['Job Title']
    .str.lower()
    .str.replace(' ', '-')
    .str.replace('(', '')
    .str.replace(')', '')
    .str.replace(',', '')
    .str.replace('/', '-'))

In [56]:
url_title

0                senior-python-developer
1                        energy-engineer
2                        legal-executive
3                 fitness-centre-manager
4                        product-manager
                     ...
95    museum-gallery-exhibitions-officer
96               radiographer-diagnostic
97                database-administrator
98                    furniture-designer
99                           ship-broker
Name: Job Title, Length: 100, dtype: str

In [57]:
url_title.loc[[95]]

95    museum-gallery-exhibitions-officer
Name: Job Title, dtype: str

In [58]:
url_title.loc[[0, 10, 22]]

0      senior-python-developer
10    software-engineer-python
22    scientist-research-maths
Name: Job Title, dtype: str

In [59]:
base = 'https://realpython.github.io/fake-jobs/jobs/'

In [60]:
full_urls = base + url_title + '-' + jobs_table.index.astype(str) + '.html'

In [61]:
full_urls.loc[[0, 10, 22]]

0       https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html
10    https://realpython.github.io/fake-jobs/jobs/software-engineer-python-10.html
22    https://realpython.github.io/fake-jobs/jobs/scientist-research-maths-22.html
dtype: str

In [62]:
(full_urls == jobs_table['Apply']).all()

np.True_

In [63]:
jobs_table

,Job Title,Company,Location,Posting Date,Apply
0,Senior Python Developer,"Payne, Roberts and Davis","Stewartbury, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html
1,Energy engineer,Vasquez-Davidson,"Christopherville, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/energy-engineer-1.html
2,Legal executive,"Jackson, Chambers and Levy","Port Ericaburgh, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/legal-executive-2.html
3,Fitness centre manager,Savage-Bradley,"East Seanview, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/fitness-centre-manager-3.html
4,Product manager,Ramirez Inc,"North Jamieview, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/product-manager-4.html
...,...,...,...,...,...
95,Museum/gallery exhibitions officer,"Nguyen, Yoder and Petty","Lake Abigail, AE",2021-04-08,https://realpython.github.io/fake-jobs/jobs/museum-gallery-exhibitions-officer-95.html
96,"Radiographer, diagnostic",Holder LLC,"Jacobshire, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/radiographer-diagnostic-96.html
97,Database administrator,Yates-Ferguson,"Port Susan, AE",2021-04-08,https://realpython.github.io/fake-jobs/jobs/database-administrator-97.html
98,Furniture designer,Ortega-Lawrence,"North Tiffany, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/furniture-designer-98.html
99,Ship broker,"Fuentes, Walls and Castro","Michelleville, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/ship-broker-99.html

In [64]:
URL = 'https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html'
response = requests.get(URL)

In [65]:
response.status_code

200

In [66]:
response.text

'<!DOCTYPE html>\n<html>\n  <head>\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1">\n    <title>Fake Python</title>\n    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">\n  </head>\n  <body>\n  <section class="section">\n    <div class="container mb-5">\n      <h1 class="title is-1">\n        Fake Python\n      </h1>\n      <p class="subtitle is-3">\n        Fake Jobs for Your Web Scraping Journey\n      </p>\n    </div>\n    <div class="container">\n    <div id="ResultsContainer" class="columns is-multiline">\n    <div class="box">\n<h1 class="title is-2">Senior Python Developer</h1>\n<h2 class="subtitle is-4 company">Payne, Roberts and Davis</h2>\n<div class="content">\n    <p>Professional asset web application environmentally friendly detail-oriented asset. Coordinate educational dashboard agile employ growth opportunity. Company programs CSS explore role. Html educational grit web application. Oversea SCRUM talented support. Web Application fast-growing communities inclusive programs job CSS. Css discussions growth opportunity explore open-minded oversee. Css Python environmentally friendly collaborate inclusive role. Django no experience oversee dashboard environmentally friendly willing to learn programs. Programs open-minded programs asset.</p>\n    <p id="location"><strong>Location:</strong> Stewartbury, AA</p>\n    <p id="date"><strong>Posted:</strong> 2021-04-08</p>\n</div>\n</div>\n\n    </div>\n    </div>\n  </section>\n  </body>\n</html>\n'

In [67]:
job_soup = BS(response.text)

In [68]:
job_soup

<!DOCTYPE html>

<html>
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>Fake Python</title>
<link href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css" rel="stylesheet"/>
</head>
<body>
<section class="section">
<div class="container mb-5">
<h1 class="title is-1">
        Fake Python
      </h1>
<p class="subtitle is-3">
        Fake Jobs for Your Web Scraping Journey
      </p>
</div>
<div class="container">
<div class="columns is-multiline" id="ResultsContainer">
<div class="box">
<h1 class="title is-2">Senior Python Developer</h1>
<h2 class="subtitle is-4 company">Payne, Roberts and Davis</h2>
<div class="content">
<p>Professional asset web application environmentally friendly detail-oriented asset. Coordinate educational dashboard agile employ growth opportunity. Company programs CSS explore role. Html educational grit web application. Oversea SCRUM talented support. Web Application fast-growing communities inclusive programs job CSS. Css discussions growth opportunity explore open-minded oversee. Css Python environmentally friendly collaborate inclusive role. Django no experience oversee dashboard environmentally friendly willing to learn programs. Programs open-minded programs asset.</p>
<p id="location"><strong>Location:</strong> Stewartbury, AA</p>
<p id="date"><strong>Posted:</strong> 2021-04-08</p>
</div>
</div>
</div>
</div>
</section>
</body>
</html>

In [69]:
print(job_soup.prettify())

<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <title>
   Fake Python
  </title>
  <link href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css" rel="stylesheet"/>
 </head>
 <body>
  <section class="section">
   <div class="container mb-5">
    <h1 class="title is-1">
     Fake Python
    </h1>
    <p class="subtitle is-3">
     Fake Jobs for Your Web Scraping Journey
    </p>
   </div>
   <div class="container">
    <div class="columns is-multiline" id="ResultsContainer">
     <div class="box">
      <h1 class="title is-2">
       Senior Python Developer
      </h1>
      <h2 class="subtitle is-4 company">
       Payne, Roberts and Davis
      </h2>
      <div class="content">
       <p>
        Professional asset web application environmentally friendly detail-oriented asset. Coordinate educational dashboard agile employ growth opportunity. Company programs CSS explore role. Html educational grit web application. Oversea SCRUM talented support. Web Application fast-growing communities inclusive programs job CSS. Css discussions growth opportunity explore open-minded oversee. Css Python environmentally friendly collaborate inclusive role. Django no experience oversee dashboard environmentally friendly willing to learn programs. Programs open-minded programs asset.
       </p>
       <p id="location">
        <strong>
         Location:
        </strong>
        Stewartbury, AA
       </p>
       <p id="date">
        <strong>
         Posted:
        </strong>
        2021-04-08
       </p>
      </div>
     </div>
    </div>
   </div>
  </section>
 </body>
</html>

In [70]:
all_p = job_soup.find_all('p')
len(all_p)

4

In [71]:
all_p[0].text.strip()

'Fake Jobs for Your Web Scraping Journey'

In [72]:
all_p[1].text.strip()

'Professional asset web application environmentally friendly detail-oriented asset. Coordinate educational dashboard agile employ growth opportunity. Company programs CSS explore role. Html educational grit web application. Oversea SCRUM talented support. Web Application fast-growing communities inclusive programs job CSS. Css discussions growth opportunity explore open-minded oversee. Css Python environmentally friendly collaborate inclusive role. Django no experience oversee dashboard environmentally friendly willing to learn programs. Programs open-minded programs asset.'

In [73]:
def get_description(url):
    response = requests.get(url)
    page_soup = BS(response.text)
    all_p = page_soup.find_all('p')
    return all_p[1].text.strip()

In [74]:
get_description('https://realpython.github.io/fake-jobs/jobs/television-floor-manager-8.html')

'At be than always different American address. Former claim chance prevent why measure too. Almost before some military outside baby interview. Face top individual win suddenly. Parent do ten after those scientist. Medical effort assume teacher wall. Significant his himself clearly very. Expert stop area along individual. Three own bank recognize special good along.'

In [75]:
jobs_table['Job Description'] = jobs_table['Apply'].apply(get_description)

In [76]:
jobs_table.head()

,Job Title,Company,Location,Posting Date,Apply,Job Description
0,Senior Python Developer,"Payne, Roberts and Davis","Stewartbury, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html,Professional asset web application environmentally friendly detail-oriented asset. Coordinate educational dashboard agile employ growth opportunity. Company programs CSS explore role. Html educational grit web application. Oversea SCRUM talented support. Web Application fast-growing communities inclusive programs job CSS. Css discussions growth opportunity explore open-minded oversee. Css Python environmentally friendly collaborate inclusive role. Django no experience oversee dashboard environmentally friendly willing to learn programs. Programs open-minded programs asset.
1,Energy engineer,Vasquez-Davidson,"Christopherville, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/energy-engineer-1.html,Party prevent live. Quickly candidate change although. Together type music hospital. Every speech support time operation wear often.
2,Legal executive,"Jackson, Chambers and Levy","Port Ericaburgh, AA",2021-04-08,https://realpython.github.io/fake-jobs/jobs/legal-executive-2.html,Administration even relate head color. Staff beyond chair recently and off. Own available buy country store build before. Already against which continue. Look road article quickly. International big employee determine positive go Congress. Level others record hospital employee toward like.
3,Fitness centre manager,Savage-Bradley,"East Seanview, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/fitness-centre-manager-3.html,Tv program actually race tonight themselves true power. Study economy night actually score from. Name care several. Good explain grow water plant perform resource. Security stock ball organization recognize civil. Pm her then nothing increase.
4,Product manager,Ramirez Inc,"North Jamieview, AP",2021-04-08,https://realpython.github.io/fake-jobs/jobs/product-manager-4.html,Traditional page a although for study anyone. Could yourself plan base rise would. Wear individual about add senior woman. Partner couple part cup few read consider. Take however ball ever laugh society technology. President stage population boy.

In [77]:
jobs_table['Job Description'][8]

'At be than always different American address. Former claim chance prevent why measure too. Almost before some military outside baby interview. Face top individual win suddenly. Parent do ten after those scientist. Medical effort assume teacher wall. Significant his himself clearly very. Expert stop area along individual. Three own bank recognize special good along.'